# Generated by Django 2.0.6 on 2018-10-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('username', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=30)),
                ('website', models.URLField()),
                ('password', models.CharField(max_length=16)),
                ('recent_passwords', models.CharField(max_length=1000)),
                ('active', models.BooleanField(default=True)),
                ('modified_date', models.DateField()),
                ('registered_date', models.DateField()),
            ],
        ),
    ]
