# Generated by Django 2.0.6 on 2018-10-06 12:09

import datetime
from django.db import migrations, models
import wallpapermanagement.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=wallpapermanagement.models.upload_image)),
                ('active', models.BooleanField(default=True)),
                ('add_date', models.DateField(default=datetime.date.today)),
                ('modified_date', models.DateField()),
            ],
        ),
    ]
