# Generated by Django 2.0.6 on 2018-10-11 07:48

import datetime
from django.db import migrations, models
import django.utils.datetime_safe
import wallpapermanagement.models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpapermanagement', '0002_auto_20181006_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('add_date', models.DateField(verbose_name='Added Date')),
                ('modified_date', models.DateField(default=datetime.date.today, verbose_name='Modified Date')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('position', models.CharField(max_length=30)),
                ('skills', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('image', models.ImageField(upload_to=wallpapermanagement.models.upload_image)),
            ],
        ),
        migrations.AddField(
            model_name='wallpapers',
            name='add_date',
            field=models.DateField(default=django.utils.datetime_safe.date.today, verbose_name='Added Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallpapers',
            name='modified_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Modified Date'),
        ),
    ]
