# Generated by Django 2.0.6 on 2018-10-06 12:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
import wallpapermanagement.models


class Migration(migrations.Migration):

    dependencies = [
        ('userauthentication', '0001_initial'),
        ('wallpapermanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallpapers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=wallpapermanagement.models.upload_image)),
                ('tags', models.TextField()),
                ('location', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('likes', models.IntegerField(default=0)),
                ('downloads', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='categories',
            name='add_date',
            field=models.DateField(verbose_name='Added Date'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=models.ImageField(upload_to=wallpapermanagement.models.upload_image, verbose_name='Category Image'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='modified_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Modified Date'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='wallpapers',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='category', to='wallpapermanagement.Categories'),
        ),
        migrations.AddField(
            model_name='wallpapers',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='userauthentication.Users'),
        ),
    ]
