# Generated by Django 2.0.6 on 2018-10-10 12:35

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallpapermanagement', '0002_auto_20181006_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('add_date', models.DateField(verbose_name='Added Date')),
                ('modified_date', models.DateField(default=datetime.date.today, verbose_name='Modified Date')),
            ],
        ),
        migrations.AddField(
            model_name='wallpapers',
            name='add_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Added Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallpapers',
            name='modified_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Modified Date'),
        ),
    ]
