# Generated by Django 2.0.6 on 2018-10-10 12:44

from django.db import migrations, models
import wallpapermanagement.models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpapermanagement', '0003_auto_20181010_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(max_length=10)),
                ('position', models.CharField(max_length=30)),
                ('skills', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('image', models.ImageField(upload_to=wallpapermanagement.models.upload_image)),
            ],
        ),
        migrations.AlterField(
            model_name='feedback',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
